### ISSUE TITLE
ERROR message in Circulation module

### ISSUE THREAD

**Issue by ilia-curtopelle** [leemordechai/FLAME#66] opened 2023-06-21 03:41 UTC
When I enter the circulation module and attempt to look at the "Summary" information for the coin find or try to graph the data, I get an error message from the pop-up window: "Error. An error occurred while processing your request."

**Comment by leemordechai** [comment] 2023-06-22 06:32
This seems to have been some temporary issue as everything works as intended for me. Could you please recheck and if this remains an issue on your side we should discuss further. Closing this issue for now.

**Closed by leemordechai** 2023-06-22 06:32 UTC
Labels: bug, Debilitating
